import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {prepareCharacterTags,appendCharacterLoras,applyCharacterLorasToWorkflow,normalizeLoraBinding} from '../character-lora.js';
import {mergePromptTags} from '../wardrobe-store.js';
const settings={characterPresets:{snow:{nameCN:'司波深雪|深雪',nameEN:'shiba miyuki',promptName:'miyuki shiba',characterTraits:'1girl',facialFeatures:'black hair, blue eyes',upperBodySFW:'slender',negative:'wrong identity',loraBindings:[{file:'characters/snow.safetensors',modelWeight:0.8,clipWeight:0,triggerWords:'miyuki shiba'}]},marin:{nameCN:'海梦',nameEN:'marin kitagawa',promptName:'kitagawa marin',facialFeatures:'blonde hair',loraBindings:[]}},characterEnablePresetId:'cast',characterEnablePresets:{cast:{characters:[{characterPresetName:'snow'},'marin']}}};
const before=structuredClone(settings);
const selected=prepareCharacterTags('1girl, shiba_miyuki, blonde hair, red eyes, smiling, holding book, library, 832x1216',settings,'海梦和深雪');
assert.deepEqual(selected.characters,['snow']);assert.equal(selected.bindings[0].clipWeight,0);assert(!selected.tag.includes('blonde hair'));assert(selected.tag.includes('holding book'));assert(selected.tag.includes('832x1216'));
const code=fs.readFileSync(new URL('../index.js',import.meta.url),'utf8');
const context=vm.createContext({console:{log(){}},extensionName:'test',extension_settings29:{test:settings},window:{},mergePromptTags});
vm.runInContext(code.slice(code.indexOf('function normalizeName('),code.indexOf('var init_characterprompt =')),context);
const expanded=context.processCharacterPrompt(selected.tag);
assert(expanded.includes('miyuki shiba'));assert(expanded.includes('black hair'));assert(!expanded.includes('$'));assert.equal(context.window.collectedCharacterNegatives,'wrong identity');
const final=appendCharacterLoras(expanded+', <lora:characters/snow:1>',selected.bindings);assert.equal((final.match(/<lora:/g)||[]).length,1);assert(final.includes(':0.8:0>'));
assert.deepEqual(prepareCharacterTags('1girl, solo, smiling',settings,'深雪坐在窗前。').characters,['snow']);
assert.deepEqual(prepareCharacterTags('1girl, smiling',settings,'深雪与海梦交谈。').characters,[]);
assert.deepEqual(prepareCharacterTags('2girls, smiling',settings,'深雪坐着。').characters,[]);
assert.deepEqual(prepareCharacterTags('1girl, smiling',settings,'image###深雪###').characters,[]);
assert.deepEqual(prepareCharacterTags('1girl, talking to shiba miyuki',settings).characters,[]);
assert.deepEqual(prepareCharacterTags('1girl, 海梦',settings,'深雪站着。').characters,['marin']);
const ref='${"name":"深雪","angle":"from behind","upperBody":"hidden","lowerBody":"sfw"}$';
assert(prepareCharacterTags('1girl, '+ref,settings).tag.includes(ref));
assert.deepEqual(prepareCharacterTags('1girl, ${"name":"海梦","upperBody":"visible","lowerBody":"visible"}$',settings).characters,[],'outfit references are not characters');
const multi=prepareCharacterTags('Scene Composition: 2girls, park; Character 1 Prompt: 深雪, red eyes, smiling|centers:0.2,0.5; Character 2 Prompt: 海梦, black hair|centers:0.8,0.5;',settings);
assert.deepEqual(multi.characters,['snow','marin']);assert(!multi.tag.includes('red eyes'));assert(multi.tag.includes('centers:0.8,0.5'));
const ambiguous=structuredClone(settings);ambiguous.characterPresets.marin.nameCN+='|深雪';assert.deepEqual(prepareCharacterTags('1girl, 深雪',ambiguous).characters,[]);
const disabled=structuredClone(settings);disabled.characterPresets.snow.loraBindings[0].enabled=false;assert.equal(prepareCharacterTags('1girl, 深雪',disabled).bindings.length,0);
assert.throws(()=>normalizeLoraBinding({file:'../bad.safetensors'}),/文件/);assert.throws(()=>normalizeLoraBinding({file:'a.safetensors',modelWeight:NaN}),/权重/);
const workflow={'4':{class_type:'CheckpointLoaderSimple',inputs:{ckpt_name:'model'}},'7':{class_type:'CLIPTextEncode',inputs:{clip:['4',1],text:final}},'8':{class_type:'VAEDecode',inputs:{vae:['4',2]}},'3':{class_type:'KSampler',inputs:{model:['4',0]}}};
applyCharacterLorasToWorkflow(workflow,selected.bindings);const [id,node]=Object.entries(workflow).find(([,n])=>n.class_type==='LoraLoader');assert.equal(node.inputs.strength_clip,0);assert.deepEqual(workflow['3'].inputs.model,[id,0]);assert.deepEqual(workflow['7'].inputs.clip,[id,1]);assert.deepEqual(workflow['8'].inputs.vae,['4',2]);assert(!workflow['7'].inputs.text.includes('<lora:'));assert.deepEqual(node.inputs.model,['4',0]);
const wei={'27':{class_type:'WeiLinPromptUI',inputs:{opt_model:['4',0],opt_clip:['4',1],positive:final}},'3':{class_type:'KSampler',inputs:{model:['27',3]}}};assert.equal(applyCharacterLorasToWorkflow(wei,selected.bindings),wei);assert.equal(Object.keys(wei).length,2);
assert.equal((appendCharacterLoras('miyuki shiba',selected.bindings).match(/miyuki shiba/g)||[]).length,1,'activation words must not repeat');
assert.equal(Object.keys(applyCharacterLorasToWorkflow(workflow,selected.bindings)).length,5,'existing connected LoRA is reused');
assert.throws(()=>applyCharacterLorasToWorkflow({'1':{class_type:'CLIPTextEncode',inputs:{}}},selected.bindings),/工作流/);
assert.deepEqual(settings,before,'matching must not mutate settings');
const preserved=structuredClone(settings),savedBindings=structuredClone(settings.characterPresets.snow.loraBindings);
const saveContext=vm.createContext({extension_settings28:{test:preserved},extensionName:'test',CHARACTER_FIELDS:['nameCN'],document:{getElementById:id=>id==='char_nameCN'?{value:'深雪'}:null},normalizeCharacterPreset(){},saveSettingsDebounced21(){}});
vm.runInContext(code.slice(code.indexOf('function saveCurrentCharacterData('),code.indexOf('function deleteCharacterPreset(')),saveContext);saveContext.saveCurrentCharacterData('snow');
assert.deepEqual(JSON.parse(JSON.stringify(preserved.characterPresets.snow.loraBindings)),savedBindings,'legacy editor preserves binding values');
assert(code.includes('characterBody: requestData.characterBody'));assert(code.includes('preset.loraBindings = (existingPreset.loraBindings'));
console.log('Character LoRA: matching, prose fallback, real preset expansion, ambiguity, visibility, multiple roles, weights, dedup, graph wiring and persistence passed.');
