import assert from 'node:assert/strict';
import {buildCharacterDraftMessages,parseCharacterDraft,CHARACTER_DRAFT_FIELDS} from '../character-draft.js';
assert.throws(()=>buildCharacterDraftMessages(' '));
assert.throws(()=>buildCharacterDraftMessages('a'.repeat(12001)));
const messages=buildCharacterDraftMessages('绿色眼睛的原创人物');assert.equal(messages[1].content,'绿色眼睛的原创人物');assert.match(messages[0].content,/creative authoring/);
const draft=Object.fromEntries(CHARACTER_DRAFT_FIELDS.map(([key])=>[key,'test']));draft.notes='补充了发型';
assert.deepEqual(parseCharacterDraft('```json\n'+JSON.stringify(draft)+'\n```'),draft);
assert.throws(()=>parseCharacterDraft(JSON.stringify({...draft,facialFeatures:[]})));
assert.throws(()=>parseCharacterDraft(JSON.stringify({...draft,nameCN:''})));
assert.throws(()=>parseCharacterDraft('[]'));
console.log('Fictional authoring: input bounds, creative prompt separation, JSON validation and required fields passed.');
