import assert from 'node:assert/strict';
import {parseCivitLink,buildCivitCandidates,planCivitImport,commitCivitImport} from '../cosji-civit.mjs';
const link=parseCivitLink('https://civitai.red/models/1145224/example?modelVersionId=2262434');
const words=['adult portrait, neutral pose, daylight, plain background','adult portrait, school uniform, standing, daylight','adult portrait, nun costume, standing, daylight','adult portrait, kimono, standing, daylight','adult portrait, armor, standing, daylight','adult portrait, blue coat, standing, daylight','adult portrait, green dress, standing, daylight','adult portrait, white jacket, standing, daylight'];
const model={id:1145224,name:'Synthetic adult ordinary-outfit test',modelVersions:[{id:2262434,name:'v1',trainedWords:words},{id:2262435,name:'v2',trainedWords:words.slice(0,5)}]};
const result=buildCivitCandidates(model,link);
assert.equal(result.selectedVersion,'2262434');assert.equal(result.versions[0].candidates.length,8);assert.equal(result.versions[1].candidates.length,5);
assert.deepEqual(result.versions[0].candidates.map(c=>c.triggerWords),model.modelVersions[0].trainedWords.map(w=>w.trim()));
assert.equal(result.versions[0].candidates[1].name,'校园制服');
assert.equal(result.versions[0].candidates[2].name,'修女装');
const ordinary=buildCivitCandidates({id:1,modelVersions:[{id:2,name:'v1',trainedWords:['blue dress','portrait']} ]},parseCivitLink('https://civitai.com/models/1'));
assert.equal(ordinary.versions[0].candidates.length,1);assert.equal(ordinary.versions[0].candidates[0].triggerWords,'blue dress, portrait');
assert.throws(()=>parseCivitLink('https://evil.example/models/1'));assert.throws(()=>parseCivitLink('https://civitai.red.evil.example/models/1'));
assert.throws(()=>buildCivitCandidates(model,{...link,versionId:'missing'}));
const target={yushe:{},cosji:{roles:[{id:'marin',name:'成年原创测试角色'}],presetRoles:{}}};
const all=result.versions.flatMap(v=>v.candidates);
assert.equal(planCivitImport(all,target,'marin').filter(c=>!c.duplicate).length,8);
assert.deepEqual(commitCivitImport(all,target,'marin'),{created:8,skipped:5});
assert.deepEqual(commitCivitImport(all,target,'marin'),{created:0,skipped:13});
const first=Object.keys(target.yushe)[0];target.yushe[first].cosjiOutfitName='已改名';target.yushe[first].fixedPrompt+='masterpiece';
assert(planCivitImport(all,target,'marin')[0].duplicate);
assert.equal(Object.keys(target.yushe).length,8);
assert.throws(()=>commitCivitImport(all,target,'removed'));
console.log('PASS: Civit trigger retention, explicit versions, 13 synthetic groups deduped to 8 outfits, repeat imports skipped, renamed presets stay deduped');
