import assert from 'node:assert/strict';
import {withCommonPrompts} from '../cosji-core.mjs';
import {normalizeCommon} from '../cosji-common.js';
assert.equal(normalizeCommon({positive:' original, '}).positive,' original, ');
assert.equal(normalizeCommon({positive:'word, <lora:existing:0.7>'}).loras[0].name,'existing');
const preset={fixedPrompt:'outfit, <lora:model:0.8>',fixedPrompt_end:'details',negativePrompt:'outfit negative',cosjiComfyUrl:'http://localhost:8188'};
const settings={cosji:{commonPrompts:{positive:' quality ',negative:' bad anatomy '}}};
const original=structuredClone(preset);
const merged=withCommonPrompts(preset,settings);
assert.equal(merged.fixedPrompt,'quality, outfit, <lora:model:0.8>');
assert.equal(merged.negativePrompt,'bad anatomy, outfit negative');
assert.equal(merged.fixedPrompt_end,'details');assert.deepEqual(preset,original);
assert.deepEqual(withCommonPrompts(preset,{}),preset);
assert.equal(withCommonPrompts({},settings).fixedPrompt,'quality');
assert.equal(withCommonPrompts({},settings).negativePrompt,'bad anatomy');
assert.equal(withCommonPrompts(merged,{}).cosjiComfyUrl,preset.cosjiComfyUrl);
console.log('PASS: shared positive prefix and negatives, empty fields, source preset unchanged');
settings.cosji.presetRoles={outfitA:'roleA',outfitB:'roleB'};
settings.cosji.selectedRole='roleB';
settings.cosji.roleCommonPrompts={roleA:{positive:'character A',negative:'avoid A'},roleB:{positive:'character B',negative:'avoid B'}};
const roleA=withCommonPrompts(preset,settings,'outfitA');
assert.equal(roleA.fixedPrompt,'quality, character A, outfit, <lora:model:0.8>');
assert.equal(roleA.negativePrompt,'bad anatomy, avoid A, outfit negative');
assert.equal(withCommonPrompts(preset,settings,'outfitB').fixedPrompt,'quality, character B, outfit, <lora:model:0.8>');
assert.equal(withCommonPrompts(preset,settings,'unknown').fixedPrompt,'quality, outfit, <lora:model:0.8>');
assert.deepEqual(preset,original);
console.log('PASS: role isolation and merge order follow actual preset role, not editor selection');
settings.cosji.commonPrompts.loras=[{name:'global.safetensors',weight:'0.8',clipWeight:'',field:'fixedPrompt'}];
settings.cosji.roleCommonPrompts.roleA.loras=[{name:'role.safetensors',weight:'0.6',clipWeight:'0.4',field:'negativePrompt'}];
const defaults=withCommonPrompts(preset,settings,'outfitA');
assert.equal(defaults.fixedPrompt,'quality, <lora:global.safetensors:0.8>, character A, outfit, <lora:model:0.8>');
assert.equal(defaults.negativePrompt,'bad anatomy, avoid A, <lora:role.safetensors:0.6:0.4>, outfit negative');
assert.ok(!withCommonPrompts(preset,settings,'outfitB').negativePrompt.includes('role.safetensors'));
assert.deepEqual(preset,original);
console.log('PASS: global and role default LoRA generation with weights, field isolation and unchanged outfit');
