import assert from 'node:assert/strict';
import {splitLoras,joinLoras,migrateCatalog,normalizeComfyUrl,resolveNativeProfile} from '../cosji-core.mjs';
const preset={fixedPrompt:'portrait, <lora:folder/model.safetensors:0.8>, red dress',fixedPrompt_end:'<lora:C:\\models\\face:1:0.5>',negativePrompt:'blur, <lora:negative:-0.5>'};
const draft=splitLoras(preset);
assert.equal(draft.loras.length,3);
assert.equal(draft.fixedPrompt,'portrait, red dress');
assert.equal(draft.loras[1].name,'C:\\models\\face');
assert.equal(draft.loras[1].clipWeight,'0.5');
assert.deepEqual(splitLoras(joinLoras(draft)),draft);
draft.loras.splice(0,1);
assert(!joinLoras(draft).fixedPrompt.includes('<lora:'));
assert(joinLoras(draft).fixedPrompt_end.includes(':1:0.5>'));
assert.throws(()=>joinLoras({...draft,loras:[{name:'x',weight:'NaN',field:'fixedPrompt'}]}));
assert.equal(splitLoras({fixedPrompt:'test <lora:invalid>'}).fixedPrompt,'test <lora:invalid>');
const settings={yushe:{legacy:{...preset}},cosji:{roles:[{id:'a',name:'角色A'}],presetRoles:{legacy:'removed'}}};
migrateCatalog(settings);assert.equal(settings.cosji.presetRoles.legacy,'uncategorized');
const before=JSON.stringify(settings);migrateCatalog(settings);assert.equal(JSON.stringify(settings),before);
assert.equal(normalizeComfyUrl(' http://127.0.0.1:8188/ '),'http://127.0.0.1:8188');
assert.throws(()=>normalizeComfyUrl('file:///C:/x'));assert.throws(()=>normalizeComfyUrl('https://user:password@host'));
const context={extensionSettings:{connectionManager:{profiles:[{id:'native',mode:'cc',api:'custom','api-url':'https://example.com/v1','secret-id':'secret-id',model:'main-model'}]}}};
const model={cosji_connection_id:'native',model:'cosji-model',api_key:'old-key',bypass_proxy:true};
const resolved=resolveNativeProfile(model,context);assert.equal(resolved.model,'cosji-model');assert.equal(resolved.secret_id,'secret-id');assert.equal(resolved.api_key,'');assert.equal(resolved.bypass_proxy,false);assert.equal(context.extensionSettings.connectionManager.profiles[0].model,'main-model');
context.extensionSettings.connectionManager.profiles[0]['api-url']='https://changed.example/v1';
assert.equal(resolveNativeProfile(model,context).api_url,'https://changed.example/v1');
context.extensionSettings.connectionManager.profiles=[];assert.equal(resolveNativeProfile(model,context).api_url,'');
console.log('PASS: LoRA roundtrip/deletion, legacy migration, URL validation, live native connection and independent models');
