import assert from 'node:assert/strict';
import {isSopClothingTag,expandSopResolvedOutfit,applySopOutfitPriority} from '../generation-sop-outfit.js';
for(const tag of ['school uniform','black pleated skirt','(white shirt:1.2)','wearing a red dress','nude','thigh_high_stockings'])assert.equal(isSopClothingTag(tag),true,tag);
for(const tag of ['holding jacket','handing a shirt','pulling skirt','clothes shop','jacket on chair','blue eyes','bare shoulders','small breasts','hair ribbon','school uniform rack','standing behind a girl in uniform'])assert.equal(isSopClothingTag(tag),false,tag);
const original='silver hair, school uniform, black skirt, holding jacket, clothes shop, sitting, small breasts, (white shirt:1.2)';
assert.equal(applySopOutfitPriority(original,'blue blouse, jeans'),'silver hair, holding jacket, clothes shop, sitting, small breasts, blue blouse, jeans');
assert.equal(applySopOutfitPriority(original,''),original);
const ref='${"name":"a","angle":"from front","upperBody":"sfw","lowerBody":"sfw"}$';
assert.equal(applySopOutfitPriority(ref+', smiling, school uniform','blue blouse'),ref+', smiling, blue blouse');
const outfit={loraTriggerWords:'trigger',upperBody:'white shirt',fullBody:'blue skirt',upperBodyBack:'shirt back',fullBodyBack:'skirt back'};
assert.equal(expandSopResolvedOutfit(outfit),'trigger, white shirt, blue skirt');
assert.equal(expandSopResolvedOutfit(outfit,{angle:'from behind',upperBody:'hidden'}),'trigger, skirt back');
assert.equal(expandSopResolvedOutfit(outfit,{upperBody:'hidden',lowerBody:'hidden'}),'trigger');
console.log('SOP outfit priority tests passed.');
