import assert from 'node:assert/strict';
import {parseSopTag,resolveRolePromptPreset,buildGenerationPlan,materializeSopWorkflow,createStandardRegionalWorkflow,resolveSopAddressSettings} from '../generation-sop.js';
const roleRef=name=>'$'+JSON.stringify({name,angle:'from front',upperBody:'sfw',lowerBody:'sfw'})+'$';
const settings={comfyuiUrl:'http://localhost:8188/',yusheid_comfyui:'scene',worker:'{}',comfyui_multi_workflow:JSON.stringify(createStandardRegionalWorkflow()),comfyui_public_person_preset:'person',yushe:{scene:{fixedPrompt:'masterpiece',fixedPrompt_end:'soft light',negativePrompt:'low quality'},person:{fixedPrompt:'detailed face',negativePrompt:'bad face'},snow:{fixedPrompt:'snow trigger',negativePrompt:'wrong snow'}},characterPresets:{snow:{nameCN:'深雪|司波深雪',negative:'wrong identity',promptPresetsByAddress:{'http://localhost:8188':'snow'}},marin:{nameCN:'海梦',promptPresetsByAddress:{'http://other:8188':'snow'}}},characterEnablePresetId:'cast',characterEnablePresets:{cast:{characters:['snow','marin']}}};
const structured=`Scene Composition:2girls, holding hands, library;Character 3 Prompt:${roleRef('深雪')}, smiling|centers:{0.25,0.5};Character 3 UC:angry;Character 8 Prompt:${roleRef('海梦')}, sitting|centers:d3;Character 8 UC:standing;`;
const expanded='Scene Composition:2girls, holding hands, library;Character 3 Prompt:black hair, white dress, smiling|centers:{0.25,0.5};Character 3 UC:angry;Character 8 Prompt:blonde hair, blue skirt, sitting|centers:d3;Character 8 UC:standing;';
const parsed=parseSopTag(structured);
assert.equal(parsed.characters[0].id,3);assert.equal(parsed.characters[1].coordinates.x,0.7000000000000001);assert(!parsed.characters[0].prompt.includes('centers'));assert.equal(parsed.characters[0].negative,'angry');
const before=structuredClone(settings);
const plan=buildGenerationPlan({rawTag:structured,preparedTag:structured,expandedTag:expanded,settings});
assert.equal(plan.mode,'regional');assert.equal(plan.count,2);assert.equal(plan.characters[0].roleKey,'snow');assert.equal(plan.characters[1].roleKey,'marin');
assert.equal(plan.characters[0].presetSource,'role');assert.equal(plan.characters[1].presetSource,'public');assert(plan.characters[0].prompt.includes('snow trigger'));assert(!plan.characters[0].prompt.includes('detailed face'));assert(plan.characters[1].prompt.includes('detailed face'));
assert.equal((plan.positive.match(/masterpiece/g)||[]).length,1);assert(plan.characters[0].negative.includes('wrong identity'));assert(!plan.characters[1].negative.includes('wrong snow'));
assert.deepEqual(settings,before);plan.characters[0].prompt='changed';assert(plan.snapshot.characters[0].prompt.includes('snow trigger'),'snapshot independent of later UI edits');
const regenerated=buildGenerationPlan({rawTag:structured,preparedTag:structured,expandedTag:expanded,settings});
const workflow=materializeSopWorkflow(settings.comfyui_multi_workflow,regenerated);
assert.equal(workflow['9'].inputs.x,0);assert.equal(workflow['11'].inputs.x,0.45000000000000007);assert.equal(typeof workflow['9'].inputs.width,'number');assert(workflow['5'].inputs.text.includes('white dress'));assert(workflow['7'].inputs.text.includes('blue skirt'));
assert(workflow['6'].inputs.text.includes('low quality'));assert(!workflow['8'].inputs.text.includes('wrong snow'));assert.equal(workflow['18'].inputs.seed,'%seed%','existing executor placeholders preserved');
const code=fn=>{try{fn();return null;}catch(error){return error.code;}};
const broken=createStandardRegionalWorkflow();broken['14'].inputs.conditioning_2=['3',0];
assert.equal(code(()=>materializeSopWorkflow(broken,regenerated)),'REGIONAL_CONTRACT_INVALID','unused character branch is not regional execution');
const missingArea=createStandardRegionalWorkflow();missingArea['9'].class_type='ConditioningCombine';assert.equal(code(()=>materializeSopWorkflow(missingArea,regenerated)),'REGIONAL_CONTRACT_INVALID');
const missingLocation=createStandardRegionalWorkflow();missingLocation['9'].inputs.x=0;missingLocation['10'].inputs.x=0;assert.equal(code(()=>materializeSopWorkflow(missingLocation,regenerated)),'REGIONAL_CONTRACT_INVALID');
assert.equal(code(()=>buildGenerationPlan({rawTag:structured,preparedTag:structured,expandedTag:expanded,settings:{...settings,comfyui_multi_workflow:''}})),'MULTI_WORKFLOW_REQUIRED');
assert.equal(code(()=>buildGenerationPlan({rawTag:'3girls',settings})),'MULTI_UNSUPPORTED');assert.equal(code(()=>buildGenerationPlan({rawTag:'2girls, smiling',settings})),'MULTI_STRUCTURE_REQUIRED');
const merged=buildGenerationPlan({rawTag:structured,preparedTag:structured,expandedTag:expanded,settings,allowMerged:true});assert.equal(merged.mode,'merged');assert.equal(merged.workflow,settings.worker);
const loras=structuredClone(settings);loras.characterPresets.snow.loraBindingsByAddress={'http://localhost:8188':[{file:'snow.safetensors',triggerWords:'snow lora'}]};
assert.equal(code(()=>buildGenerationPlan({rawTag:structured,preparedTag:structured,expandedTag:expanded,settings:loras})),'GLOBAL_LORA_CONFIRM');
const global=buildGenerationPlan({rawTag:structured,preparedTag:structured,expandedTag:expanded,settings:loras,allowGlobalLoras:true});assert.equal(global.bindings.length,1);assert(global.warnings.some(value=>value.includes('全局')));
const missing=structuredClone(settings);missing.characterPresets.snow.promptPresetsByAddress['http://localhost:8188']='deleted';assert.equal(code(()=>resolveRolePromptPreset(missing.characterPresets.snow,missing)),'PRESET_MISSING');
const changedService={...settings,comfyuiUrl:'http://new:8188'};assert.equal(resolveRolePromptPreset(settings.characterPresets.snow,changedService).presetSource,'public');
const duplicate=structuredClone(settings);duplicate.characterPresets.marin.nameCN='海梦|深雪';assert.equal(code(()=>buildGenerationPlan({rawTag:roleRef('深雪'),settings:duplicate})),'IDENTITY_CONFLICT');
const unknown=buildGenerationPlan({rawTag:'1girl, original hero, red hair',settings});assert.equal(unknown.characters[0].roleKey,null);assert(unknown.positive.includes('red hair'));assert(unknown.warnings.length);
const single=buildGenerationPlan({rawTag:'1girl, 深雪',preparedTag:roleRef('深雪'),expandedTag:'black hair, smiling',settings,selection:{characters:['snow']}});assert.equal(single.mode,'single');assert(single.positive.includes('snow trigger'));
assert.equal(parseSopTag('Scene Composition:library;Character 1 Prompt:smiling').characters.length,1,'trailing semicolon optional');
assert.equal(code(()=>parseSopTag('Character 1 Prompt:smiling;Character 1 Prompt:sitting;')),'STRUCTURE_INVALID');
// Legacy references and canonical keys selected in the ambiguity dialog remain routable.
const canonical=structuredClone(settings);canonical.characterPresets.marin.nameCN='海梦|snow';
const canonicalPlan=buildGenerationPlan({rawTag:roleRef('snow'),expandedTag:'black hair',settings:canonical});assert.equal(canonicalPlan.characters[0].roleKey,'snow');
const legacy=buildGenerationPlan({rawTag:'1girl, $深雪-sfw-upperbody-lowerbody$, smiling',expandedTag:'1girl, black hair, smiling',settings});assert.equal(legacy.characters[0].roleKey,'snow');assert(legacy.characters[0].prompt.includes('snow trigger'));
const flatPair=`2girls, ${roleRef('深雪')}, ${roleRef('海梦')}, holding hands`;
assert.equal(code(()=>buildGenerationPlan({rawTag:flatPair,settings})),'MULTI_STRUCTURE_REQUIRED');
const flatMerged=buildGenerationPlan({rawTag:flatPair,expandedTag:'2girls, black hair, blonde hair, holding hands',settings,allowMerged:true});assert.equal(flatMerged.characters.length,2);assert.equal(flatMerged.characters[0].roleKey,'snow');assert.equal(flatMerged.characters[1].roleKey,'marin');assert(flatMerged.positive.includes('snow trigger'));assert(flatMerged.positive.includes('detailed face'));assert.equal((flatMerged.positive.match(/holding hands/g)||[]).length,1);assert(!flatMerged.positive.includes('$'));
assert.equal(code(()=>buildGenerationPlan({rawTag:`${roleRef('深雪')}, ${roleRef('海梦')}`,settings})),'MULTI_STRUCTURE_REQUIRED','multiple explicit identities imply multiple people even without a count tag');
const halfKnown=buildGenerationPlan({rawTag:`2girls, ${roleRef('深雪')}`,expandedTag:'2girls, black hair, original companion',settings,allowMerged:true});assert.equal(halfKnown.characters[1].roleKey,null);assert.equal(halfKnown.characters[1].presetSource,'public');

const scoped={...settings,comfyui_sop_by_address:{'http://localhost:8188':{public_person_preset:'snow',multi_workflow:settings.comfyui_multi_workflow,multi_lora_mode:'global',region_preview:true}}};
const localSettings=resolveSopAddressSettings(scoped);assert.equal(localSettings.comfyui_public_person_preset,'snow');assert.equal(localSettings.comfyui_multi_lora_mode,'global');assert.equal(localSettings.comfyui_region_preview,true);
const newAddress=resolveSopAddressSettings({...scoped,comfyuiUrl:'http://new:8188/'});assert.equal(newAddress.comfyui_public_person_preset,'');assert.equal(newAddress.comfyui_multi_workflow,'');assert.equal(newAddress.comfyui_multi_lora_mode,'ask');assert.equal(newAddress.comfyui_region_preview,false);
assert.equal(resolveRolePromptPreset(scoped.characterPresets.marin,scoped).presetId,'snow');
assert.equal(code(()=>buildGenerationPlan({rawTag:structured,preparedTag:structured,expandedTag:expanded,settings:{...scoped,comfyuiUrl:'http://new:8188'}})),'MULTI_WORKFLOW_REQUIRED');
assert.equal(resolveSopAddressSettings(settings).comfyui_public_person_preset,'person','legacy settings remain available before migration');
assert.equal(settings.comfyui_sop_by_address,undefined,'resolution never mutates settings');
console.log('generation SOP: routing, fallback, identities, region wiring, snapshots and explicit downgrade checks passed');
