import assert from 'node:assert/strict';
import {validateSopLoraFiles,validateSopWorkflowNodes,resolveSopLoraBindings} from '../generation-sop-validation.js';
import {createStandardRegionalWorkflow} from '../generation-sop.js';
const code=fn=>{try{fn();return null;}catch(error){return error.code;}};
const character=(fields={})=>({id:1,name:'深雪',prompt:'',negative:'',bindings:[],...fields});
const plan={characters:[character({bindings:[{file:'cast\\snow.safetensors'}],prompt:'<lora:snow:0.7>, <wlr:detail:1:0.5>'})],scenePrompt:'<lora:quality:0.8>',sceneNegative:'<wlr:negative:1>'};
const files=['cast/snow.safetensors','extra/detail.safetensors','quality.safetensors','negative.safetensors'];
const before=JSON.stringify(plan);
assert.deepEqual(validateSopLoraFiles(plan,files).map(item=>item.file),['cast/snow.safetensors','cast/snow.safetensors','extra/detail.safetensors','quality.safetensors','negative.safetensors']);
assert.equal(JSON.stringify(plan),before,'validation never mutates the plan');
assert.deepEqual(validateSopLoraFiles({characters:[]},undefined),[],'no LoRA does not need catalog');
assert.equal(code(()=>validateSopLoraFiles(plan,undefined)),'LORA_CATALOG_UNAVAILABLE');
assert.equal(code(()=>validateSopLoraFiles(plan,[])),'LORA_FILE_MISSING');
assert.throws(()=>validateSopLoraFiles(plan,[]),/深雪.*cast/,'error identifies the role and file');
assert.equal(code(()=>validateSopLoraFiles({characters:[character({prompt:'<lora:snow:1>'})]},['a/snow.safetensors','b/snow.safetensors'])),'LORA_FILE_AMBIGUOUS');
assert.equal(validateSopLoraFiles({characters:[character({prompt:'<lora:a/snow:1>'})]},['a/snow.safetensors','b/snow.safetensors'])[0].file,'a/snow.safetensors');
assert.equal(code(()=>validateSopLoraFiles({characters:[character({prompt:'<lora:wrong/snow:1>'})]},['a/snow.safetensors'])),'LORA_FILE_MISSING','never drop an explicitly requested folder');
assert.equal(validateSopLoraFiles({characters:[character({prompt:'<LORA:SNOW:1>'})]},[{name:'snow.safetensors'}])[0].file,'snow.safetensors');
assert.deepEqual(validateSopLoraFiles({characters:[character({bindings:[{file:'missing.safetensors',enabled:false}]})]},[]),[]);
assert.equal(code(()=>validateSopLoraFiles({characters:[],bindings:[{file:'orphan.safetensors'}]},[])),'LORA_FILE_MISSING');
assert.throws(()=>validateSopLoraFiles({characters:[],scenePrompt:'<wlr:missing:1>'},[]),/公共画面预设.*missing/);
assert.throws(()=>validateSopLoraFiles({characters:[character({negative:'<lora:bad:1>'})]},[]),/深雪.*bad/);
const workflow=createStandardRegionalWorkflow(),info=Object.fromEntries(Object.values(workflow).map(node=>[node.class_type,{}]));
assert.equal(validateSopWorkflowNodes(workflow,info),true);
assert.equal(validateSopWorkflowNodes(JSON.stringify(workflow),info),true);
const incomplete={...info};delete incomplete.ConditioningSetAreaPercentage;
assert.equal(code(()=>validateSopWorkflowNodes(workflow,incomplete)),'WORKFLOW_NODE_MISSING');
assert.throws(()=>validateSopWorkflowNodes(workflow,incomplete),/#9 ConditioningSetAreaPercentage/);
assert.equal(code(()=>validateSopWorkflowNodes(workflow,undefined)),'NODE_CATALOG_UNAVAILABLE');
assert.equal(code(()=>validateSopWorkflowNodes('{',info)),'WORKFLOW_INVALID');
assert.equal(code(()=>validateSopWorkflowNodes({nodes:[]},info)),'WORKFLOW_INVALID','UI workflow export rejected');
assert.equal(code(()=>validateSopWorkflowNodes([],info)),'WORKFLOW_INVALID');
console.log('SOP validation: LoRA resolution, ambiguity, ownership and workflow node checks passed');

const native=resolveSopLoraBindings({characters:[character({bindings:[{file:'cast/snow.safetensors',modelWeight:0.7,clipWeight:0.5,triggerWords:'snow hero'}],prompt:'<lora:snow:0.7:0.5>, <wlr:detail:1>'})],scenePrompt:'<lora:quality:0.8>'},files);
assert.equal(native.length,3);assert.deepEqual(native[0],{file:'cast/snow.safetensors',modelWeight:0.7,clipWeight:0.5,triggerWords:'snow hero',enabled:true});
assert.equal(native[1].clipWeight,1);assert.equal(native[2].clipWeight,0.8);
assert.equal(code(()=>resolveSopLoraBindings({characters:[character({bindings:[{file:'cast/snow.safetensors',modelWeight:0.7,clipWeight:0.5}],prompt:'<lora:snow:1>'})]},files)),'LORA_CONFLICT');
assert.equal(code(()=>resolveSopLoraBindings({characters:[character({prompt:'<wlr:snow:1:1:1>'})]},files)),'LORA_PARAMETERS_UNSUPPORTED');
assert.equal(code(()=>resolveSopLoraBindings({characters:[character({prompt:'<lora:snow:nope>'})]},files)),'LORA_WEIGHT_INVALID');
assert.equal(code(()=>resolveSopLoraBindings({characters:[character({prompt:'<lora:snow:3>'})]},files)),'LORA_WEIGHT_INVALID');
assert.deepEqual(resolveSopLoraBindings({characters:[]},undefined),[]);
console.log('SOP LoRA materialization: native bindings, trigger preservation, conflicts and unsupported params passed');
