import { mergePromptTags } from '../wardrobe-store.js';
import assert from 'node:assert/strict';
import { library, roleCombinations, bindCombination, unbindCombination, scene, latestBody, resolveWear, applyWear, matchOutfits, selectedOutfitKeys, saveCover, parseCivitLink, civitGroups, importCivitGroups } from '../wardrobe-store.js';
const s={characterPresets:{Alice:{nameCN:'爱丽丝|小爱',nameEN:'Alice',outfits:['水手服','连衣裙'],photoImageIds:['old']}},outfitPresets:{水手服:{nameCN:'水手服',upperBody:'navy sailor shirt',photoImageIds:['ref']},连衣裙:{nameCN:'连衣裙',upperBody:'black dress'}},characterCommonPresetId:'list',characterCommonPresets:{list:{characters:['Alice']}}};
const ctx={chatId:'a',characterId:0,chat:[{is_user:false,mes:'爱丽丝穿着水手服。',swipe_id:0}]},w=library(s),r=Object.values(w.roles)[0],c=Object.values(w.combinations).find(c=>c.name==='水手服'),dress=Object.values(w.combinations).find(c=>c.name==='连衣裙');
assert.deepEqual(s.characterPresets.Alice.photoImageIds,['old']);assert.deepEqual(w.backup.outfits.水手服.photoImageIds,['ref']);assert.equal(resolveWear(s,ctx,r.id),null,'migration must not silently pick first outfit');
assert.equal(matchOutfits(s,ctx,r.id).length,1);assert.equal(Object.keys(scene(s,ctx).roles).length,0,'matching never applies');
r.defaultComboId=dress.id;applyWear(s,ctx,r.id,c.id,false);assert.equal(resolveWear(s,ctx,r.id).comboId,c.id);assert.equal(r.defaultComboId,dress.id);assert.deepEqual(selectedOutfitKeys(s,ctx),['水手服']);
ctx.chat.push({is_user:false,mes:'她坐下了。'});assert.equal(resolveWear(s,ctx,r.id).comboId,c.id,'valid source persists across later replies');ctx.chat[0].swipe_id=1;assert.equal(resolveWear(s,ctx,r.id).comboId,dress.id,'swipe invalidates previous source');
applyWear(s,ctx,r.id,c.id,true);ctx.chat[1].mes='爱丽丝穿着连衣裙。';assert.equal(resolveWear(s,ctx,r.id).comboId,c.id,'manual lock preserved');assert.equal(resolveWear(s,{...ctx,chatId:'b'},r.id).comboId,dress.id,'chat isolation');
s.characterPresets.Renamed=s.characterPresets.Alice;delete s.characterPresets.Alice;library(s);assert.equal(w.roles[r.id].key,'Renamed','stable ID on unambiguous rename');
saveCover(s,{roleId:r.id,comboId:c.id},'first');saveCover(s,{roleId:r.id,comboId:c.id},'second');assert.equal(w.covers[r.id+':'+c.id].current,'first');saveCover(s,{roleId:r.id,comboId:c.id},'third',true);assert.equal(w.covers[r.id+':'+c.id].first,'first');
assert.deepEqual(parseCivitLink('https://civitai.red/models/1092840/example?modelVersionId=1227619'),{id:1092840,versionId:1227619});
const model={id:1,name:'model',type:'LORA'},version={id:2,baseModel:'Illustrious',trainedWords:['activation, black dress','activation, blue dress']};const groups=civitGroups(model,version);groups.forEach((g,i)=>{g.name='服装'+i;g.description=g.raw.split(',').slice(1).join(',').trim();});assert.equal(importCivitGroups(s,groups).filter(x=>!x.reused).length,2,'same activation does not merge different groups');assert.equal(importCivitGroups(s,groups).filter(x=>x.reused).length,2);assert.equal(Object.values(w.outfits).find(o=>o.civit).civit.raw,'activation, black dress');
console.log('Wardrobe: migration, stable IDs, defaults, chat isolation, source invalidation, manual lock, matching, selected-only prompts, covers and Civit dedup passed.');
// Exercise the installed prompt assembly, including old templates without an outfits field.
const { readFile } = await import('node:fs/promises'); const vm = await import('node:vm');
const source = await readFile(new URL('../index.js',import.meta.url),'utf8');
function extract(name){const start=source.indexOf('function '+name+'(');assert(start>=0);const next=source.slice(start+1).search(/\n(?:async )?function /);return source.slice(start,next<0?undefined:start+1+next);}
const promptSettings={characterPresets:{Alice:{nameCN:'Alice',outfits:['water','dress']}},outfitPresets:{water:{nameCN:'water',upperBody:'navy shirt'},dress:{nameCN:'dress',upperBody:'black dress'}},characterCommonPresetId:'a',characterCommonPresets:{a:{characters:['Alice']}},outfitEnablePresetId:'all',outfitEnablePresets:{all:{outfits:['water','dress']}}};
const renderContext={mergePromptTags,extension_settings25:{test:promptSettings},extensionName:'test',PLACEHOLDER_RE:/\{([a-zA-Z0-9_]+)\}/g,wardrobeOutfits:()=>['water'],wardrobeSelectedOutfits:()=>['water'],getActiveInjectionTemplates:()=>({commonCharacterListTemplate:'{nameCN}',innerOutfitTemplate:'{nameCN}: {upperBody}',enableOutfitListTemplate:'{upperBody}'})};
const code=['normalizeCharacterEnableEntry','getCharacterPromptData','getOutfitPromptData','applyInjectionTemplate','renderCharacterOutfitsText','generateCommonCharacterListText','generateOutfitEnableListText'].map(extract).join('\n');
const output=vm.runInNewContext(code+'\n[generateCommonCharacterListText(),generateOutfitEnableListText()]',renderContext);assert(output[0].includes('navy shirt'));assert(!output.join(' ').includes('black dress'));
renderContext.getActiveInjectionTemplates=()=>({commonCharacterListTemplate:'{nameCN} {outfits}',innerOutfitTemplate:'{upperBody}',enableOutfitListTemplate:'{upperBody}'});const once=vm.runInNewContext(code+'\ngenerateCommonCharacterListText()',renderContext);assert.equal(once.match(/navy shirt/g).length,1,'outfits placeholder must not duplicate selected clothes');
console.log('Installed prompt renderer: common roles carry selected clothing, full wardrobe is excluded, template placeholder appears once.');
const colourContext={chatId:'colour',characterId:0,chat:[{is_user:false,mes:'爱丽丝穿着黑色连衣裙。'}]};assert.equal(matchOutfits(s,colourContext,r.id).length,1,'name or explicit colour+garment can suggest');colourContext.chat[0].mes='爱丽丝站在黑色墙前。';assert.equal(matchOutfits(s,colourContext,r.id).length,0,'colour without clothing type must not suggest an outfit');
const before=JSON.stringify(s.outfitPresets);assert.throws(()=>importCivitGroups(s,[groups[0],{...groups[1],name:''}]),/不能为空/);assert.equal(JSON.stringify(s.outfitPresets),before,'invalid batch must not partially save');

const scoped={characterPresets:{A:{nameCN:'A',outfits:['shirt']},B:{nameCN:'B',outfits:[]}},outfitPresets:{shirt:{nameCN:'shirt',upperBody:'blue shirt'},dress:{nameCN:'dress',upperBody:'black dress'}}};const sw=library(scoped),a=Object.values(sw.roles).find(r=>r.key==='A'),b=Object.values(sw.roles).find(r=>r.key==='B'),shirt=Object.values(sw.combinations).find(c=>c.name==='shirt'),extra=Object.values(sw.combinations).find(c=>c.name==='dress');
assert.deepEqual(roleCombinations(scoped,a.id).map(c=>c.id),[shirt.id]);assert.deepEqual(roleCombinations(scoped,b.id),[]);assert.throws(()=>applyWear(scoped,{chatId:'scoped',chat:[]},b.id,shirt.id),/先把/);
bindCombination(scoped,b.id,shirt.id);assert.deepEqual(scoped.characterPresets.B.outfits,['shirt']);bindCombination(scoped,a.id,extra.id);assert.deepEqual(roleCombinations(scoped,b.id).map(c=>c.id),[shirt.id]);
const onlyB={chatId:'scoped',chat:[{mes:'B wears dress.',is_user:false}]};assert.deepEqual(matchOutfits(scoped,onlyB,b.id),[],'matching cannot use another role wardrobe');
applyWear(scoped,onlyB,b.id,shirt.id,true);sw.roles[b.id].defaultComboId=shirt.id;unbindCombination(scoped,b.id,shirt.id);assert.equal(resolveWear(scoped,onlyB,b.id),null);assert.equal(scoped.outfitPresets.shirt.upperBody,'blue shirt');assert.equal(roleCombinations(scoped,a.id).length,2,'unlink does not modify other roles');
const custom='custom';sw.combinations[custom]={...shirt,id:custom,name:'alternate shirt'};bindCombination(scoped,a.id,custom);unbindCombination(scoped,a.id,shirt.id);assert(!roleCombinations(scoped,a.id).some(c=>c.id===shirt.id),'a removed combination must not resurrect via legacy bindings');assert(roleCombinations(scoped,a.id).some(c=>c.id===custom));
console.log('Per-role wardrobes: legacy migration, own inventory matching, explicit reuse, isolated additions/removal and retained shared clothes passed.');
scoped.outfitPresets['renamed shirt']=scoped.outfitPresets.shirt;delete scoped.outfitPresets.shirt;library(scoped);assert(!roleCombinations(scoped,a.id).some(c=>c.id===shirt.id),'renaming must not re-add an unlinked combination');assert(roleCombinations(scoped,a.id).some(c=>c.id===custom));assert(scoped.characterPresets.A.outfits.includes('renamed shirt'),'legacy references follow stable outfit rename');

const {deleteLibraryItem,restoreLibraryItem,paginateItems}=await import('../wardrobe-store.js');
const recovery={characterPresets:{A:{nameCN:'A',outfits:['shirt']},B:{nameCN:'B',outfits:['shirt']}},outfitPresets:{shirt:{nameCN:'shirt',upperBody:'blue shirt',photoImageIds:['photo']}},characterCommonPresets:{list:{characters:['A','B']}},characterCommonPresetId:'list',outfitEnablePresets:{list:{outfits:['shirt']}}};
const rw=library(recovery),ra=Object.values(rw.roles).find(r=>r.key==='A'),rc=Object.values(rw.combinations)[0];ra.defaultComboId=rc.id;applyWear(recovery,{chatId:'recover',chat:[]},ra.id,rc.id,true);saveCover(recovery,{roleId:ra.id,comboId:rc.id},'cover');
const removed=deleteLibraryItem(recovery,'outfits',Object.values(rw.outfits)[0].id);assert(!recovery.outfitPresets.shirt);assert.deepEqual(recovery.characterPresets.A.outfits,[]);assert(!rw.combinations[rc.id]);assert(!rw.scenes['recover:none'].roles[ra.id]);assert.equal(rw.covers[ra.id+':'+rc.id].first,'cover');
restoreLibraryItem(recovery,removed.id);assert.deepEqual(recovery.characterPresets.A.outfits,['shirt']);assert.deepEqual(recovery.characterPresets.B.outfits,['shirt']);assert.equal(ra.defaultComboId,rc.id);assert.equal(resolveWear(recovery,{chatId:'recover',chat:[]},ra.id).source.default,true);assert.deepEqual(recovery.outfitPresets.shirt.photoImageIds,['photo']);
const deletedRole=deleteLibraryItem(recovery,'roles',ra.id);assert.deepEqual(recovery.characterCommonPresets.list.characters,['B']);assert(recovery.outfitPresets.shirt);restoreLibraryItem(recovery,deletedRole.id);assert(recovery.characterCommonPresets.list.characters.includes('A'));
const again=deleteLibraryItem(recovery,'roles',ra.id);recovery.characterPresets.A={nameCN:'new A',outfits:[]};const beforeRestore=JSON.stringify(recovery);assert.throws(()=>restoreLibraryItem(recovery,again.id),/同名/);assert.equal(recovery.characterPresets.A.nameCN,'new A');assert(rw.trash.some(x=>x.id===again.id));
assert.deepEqual(paginateItems(Array.from({length:37},(_,i)=>i),99,12).items,[36]);assert.equal(paginateItems([],3,12).page,1);assert.equal(paginateItems([1],-1,NaN).size,12);
assert.equal(mergePromptTags('MarinBikini, blue shirt','blue shirt, denim shorts'),'MarinBikini, blue shirt, denim shorts');
const tagPreset=importCivitGroups(recovery,civitGroups({id:3,name:'activation',type:'LORA'},{id:4,trainedWords:['MarinBikini, blue shirt']}))[0];assert.equal(recovery.outfitPresets[tagPreset.key].loraTriggerWords,'MarinBikini, blue shirt');
const characterData=vm.runInNewContext(extract('getCharacterPromptData')+'\ngetCharacterPromptData',{mergePromptTags});const data=characterData({nameCN:'喜多川海梦|海梦',nameEN:'Marin|Kitagawa',promptName:'kitagawa marin',characterTraits:'blonde hair'});assert.equal(data.nameEN,'kitagawa marin');assert.equal(data.traits,'kitagawa marin, blonde hair');
const outfitData=vm.runInNewContext(extract('getOutfitPromptData')+'\ngetOutfitPromptData',{mergePromptTags});assert.equal(outfitData({upperBody:'MarinBikini, blue shirt',loraTriggerWords:'MarinBikini'}).upperBody,'MarinBikini, blue shirt');
console.log('Deletion/recovery: shared associations, defaults, stale chat removal, media preservation and collision safety; pagination and actual prompt-name/LoRA rendering passed.');
// Exercise the installed parser that produces the final positive prompt used by ComfyUI.
const parserCharacter={nameCN:'喜多川海梦',promptName:'kitagawa marin',characterTraits:'blonde hair',outfits:['shirt']};const parserOutfit={nameCN:'shirt',loraTriggerWords:'MarinBikini',upperBody:'MarinBikini, blue shirt',fullBody:'denim shorts'};
const parserSettings={characterPresets:{Marin:parserCharacter},outfitPresets:{shirt:parserOutfit}};
const parsePrompt=vm.runInNewContext(extract('processCharacterPrompt')+'\nprocessCharacterPrompt',{mergePromptTags,window:{},console:{log(){}},extension_settings29:{test:parserSettings},extensionName:'test',normalizeName:x=>x.toLowerCase(),findBestCharacterMatch:()=>parserCharacter,findBestOutfitMatch:()=>parserOutfit,collectNegativeToGlobal(){}});
for(const text of ['$喜多川海梦-sfw-upperbody$', '$'+JSON.stringify({name:'喜多川海梦',angle:'front',upperBody:'sfw'})+'$'])assert(parsePrompt(text).includes('kitagawa marin, blonde hair'));
for(const text of ['$shirt-upperbody-lowerbody$', '$'+JSON.stringify({name:'shirt',upperBody:'visible',lowerBody:'visible'})+'$']){const prompt=parsePrompt(text);assert.equal(prompt.match(/MarinBikini/g).length,1);assert(prompt.includes('blue shirt'));}
assert(parsePrompt('$shirt-lowerbody$').includes('MarinBikini, denim shorts'));
const preserved={characterPresets:{Marin:{...parserCharacter,wikiNameSource:{source:'https://en.wikipedia.org/wiki/Marin_Kitagawa'}}}};
const saveCharacter=vm.runInNewContext(extract('saveCurrentCharacterData')+'\nsaveCurrentCharacterData',{extension_settings28:{test:preserved},extensionName:'test',CHARACTER_FIELDS:['nameCN'],document:{getElementById:id=>id==='char_nameCN'?{value:'喜多川海梦'}:null},normalizeCharacterPreset(){},saveSettingsDebounced21(){}});saveCharacter('Marin');assert.equal(preserved.characterPresets.Marin.promptName,'kitagawa marin');assert(preserved.characterPresets.Marin.wikiNameSource.source.includes('Marin_Kitagawa'));
console.log('ComfyUI final prompt parser: JSON and legacy roles, deduplicated activation for upper/lower outfit branches, and legacy editor field retention passed.');
